### PR TITLE
fix(scanner): make security score strict and security-only

### LINKED ISSUE #129: [Feature]: Security Scoring need revisit
### Pre-Submission Checklist

- [x] I have searched existing issues and this feature has not been requested.

### Problem Statement

The score is usually higher, and sometimes with "Passed with Notes."

### Proposed Solution

Be more strict and give 10/10 only if found nothing. also - the other criterias like length of flies, etc, not related to security at all.

### Alternatives Considered

_No response_

### Priority

Medium — would be a meaningful improvement

### Affected Areas

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by elad12390**
## Summary
- tighten security scoring so 10/10 is only possible when scanner findings are present and count is zero
- separate non-security quality checks from the security score while preserving quality details visibility
- pass all scanner findings (including medium/low) into score computation and add strict regression coverage

## IDD/BDD
- updated intent constraints in `.idd/modules/scan/INTENT.md` and `.idd/modules/scanner-stages/INTENT.md`
- added/updated behavior scenarios in `.bdd/features/scanner-stages/scanner-stages.feature`
- documented resolution in `.bdd/qa/resolutions/005-security-score-strictness-gh-129.md`

## Verification
- `bun x vitest packages/web/lib/__tests__/audit-score.test.ts packages/web/lib/__tests__/audit-score-security-strict.test.ts`
- `just test-python`
- `lsp_diagnostics` clean on changed files

Fixes #129

### CODE REVIEW

File: packages/web/lib/audit-score.ts [hunk 1]
```diff
@@ -131,19 +144,37 @@ export function computeAuditScore(input: AuditScoreInput): AuditScoreResult {
...
-    makeDetail('Permissions declared', permissionsDeclared, 1),
-    makeDetail('No security issues', noSecurityIssues, 2),
-    makeDetail('Permission extraction match', permissionMatch, 2),
-    makeDetail('File count reasonable', fileCountOk, 1),
-    makeDetail('README documentation', readmePresent, 1),
-    makeDetail('Package size reasonable', sizeOk, 1)
+    makeDetail('quality', 'SKILL.md present', skillMdPresent, 1),
+    makeDetail('quality', 'Description present', descriptionPresent, 1),
+    makeDetail('quality', 'Permissions declared', permissionsDeclared, 1),
+    makeDetail('security', 'No security findings', noSecurityIssues, 10),
```
Comment (WolfieLeader) [inline packages/web/lib/audit-score.ts]: `maxPoints: 10` here breaks the contract that `sum(details.points)` reconstructs `score`.

For a clean skill: `score=10` but `sum(details.points)=18` (10+2+1+1+1+1+1+1). For one medium finding: this row shows `{points: 0, maxPoints: 10}` implying a 10-point loss, but the actual penalty from `getSeverityPenalty('medium')` is only 3.

Downstream, `buildScoreCriteria()` in `apps/web-tanstack/src/screens/skills/skill-detail-helpers.tsx` is a separate scoring implementation that still assigns `maxPoints: 2` for "No critical/high security issues" — the two implementations are now divergent and the breakdown UI will show numbers that don't match the stored `auditScore`.

Consider either:
- Making `details` purely informational (drop `points`/`maxPoints`, add a `severity` or `penalty` field instead)
- Or keeping `maxPoints` values aligned with the actual score contribution so the sum still holds

File: packages/web/lib/audit-score.ts [hunk 2]
```diff
@@ -131,19 +144,37 @@ export function computeAuditScore(input: AuditScoreInput): AuditScoreResult {
...
+    makeDetail('quality', 'File count reasonable', fileCountOk, 1),
+    makeDetail('quality', 'README documentation', readmePresent, 1),
+    makeDetail('quality', 'Package size reasonable', sizeOk, 1)
   ];
 
-  // Score = sum of awarded points, clamped to [0, 10]
-  const rawScore = details.reduce((sum, d) => sum + d.points, 0);
-  const score = Math.max(0, Math.min(10, rawScore));
+  // Security score calculation (non-security checks intentionally excluded)
+  let score = hasFindingsData ? 10 : 5;
```
Comment (WolfieLeader) [inline packages/web/lib/audit-score.ts]: When `analysisResults` is `null` (scan didn't run or failed), this gives `score = 5`, then the 9.9 cap at line 174 fires too (`!(false && ...)` is true), producing a final score of exactly 5.0.

Both `confirm/route.ts` (lines 268 and 291) and `rescan.ts` hit this path on scan failure — they pass `analysisResults: null` and write the resulting score to `skillVersions.auditScore`. The old behavior gave null analysis a default pass (+2 for security, +2 for permissions), letting well-structured skills score up to 10. Now all scan-failed skills silently get 5.0.

Is this intentional? If so, worth documenting in the resolution doc and pinning the expected value in a test. If not, consider a higher fallback (e.g., `hasFindingsData ? 10 : 8`) to preserve the "benefit of the doubt" for infrastructure failures.

File: packages/web/lib/__tests__/audit-score.test.ts [hunk 3]
```diff
@@ -1,479 +1,99 @@
...
-      const input = perfectInput();
-      input.manifest.name = '';
-      const result = computeAuditScore(input);
-      const check = result.details.find((d) => d.check.toLowerCase().includes('skill.md'));
-      expect(check).toBeDefined();
-      expect(check?.passed).toBe(false);
-      expect(check?.points).toBe(0);
-    });
+    const noScan = computeAuditScore(buildInput({ analysisResults: null }));
+    expect(noScan.score).toBeLessThan(10);
```
Comment (WolfieLeader) [inline packages/web/lib/__tests__/audit-score.test.ts]: This assertion is too loose — `toBeLessThan(10)` passes for any value from `-Infinity` to `9.9`. It doesn't verify that the no-scan fallback (currently 5.0) is intentional or correct.

Consider pinning: `expect(noScan.score).toBe(5)` — or at minimum bounding it: `expect(noScan.score).toBeGreaterThanOrEqual(3)`. That way if the fallback logic changes unintentionally, the test catches it.

**Review by WolfieLeader — APPROVED** [review]
